### ISSUE TITLE
CLI install setting own GOPATH

### ISSUE THREAD

**Issue by crmadrig** [TIBCOSoftware/dovetail#68]
Hi,

Looking at the instructions set here: https://tibcosoftware.github.io/dovetail/getting-started/getting-started-cli/ I see you need to set your GOPATH param and add GOPATH/bin to your PATH param. I've done that but when i try to run the curl install command found on the page, it sets my GOPATH to the current directory i'm in, completely ignoring the variable i had set previously.

<img width="1131" alt="screen shot 2018-12-21 at 1 31 30 pm" src="https://user-images.githubusercontent.com/15268881/50364440-c98e0480-0524-11e9-8d18-d3eccad5574b.png">

Once the install is done, it has also change the GOPATH variable for the shell i'm currently in.

I'm assuming this is unintended since the instructions ask you to set your GOPATH.

Thanks,
Cris

**Comment by torresashjian** [comment]
Yes @crmadrig we are fixing this issue in next release 0.1.3 soon! Thanks for pointing this out.

**Comment by torresashjian** [comment]
Fixed in 0.1.3
