### ISSUE TITLE
Deployment of smart contracts from Dovetail Studio

### ISSUE THREAD

**Issue by torresashjian** [TIBCOSoftware/dovetail#70]
We need to be able to deploy smart contracts directly from Dovetail Studio, the following tasks are needed:

- [ ] Add new build type in Dovetail studio

- [ ] Deploy smart contracts (https://github.com/TIBCOSoftware/dovetail-cli/issues/23)

- [ ] Add needed services to connect to the smart contract from the cli

**Comment by yxuco** [comment]
CLI approach for hyperledger fabric is already implemented that takes an app JSON file exported from the dovetail studio, and generate the chaincode, and then install and instantiate it on a fabric network.

However, need to discuss the best way to make it work from the studio.  It is possible to wrap the CLI functions as REST APIs, and so the studio can simply post the app.json file to the API server, which will generate code, install and instantiate the chaincode.
