### ISSUE TITLE
model vs. models on https://tibcosoftware.github.io/dovetail/labs/iou-smart-app/ - step 1.2

### ISSUE THREAD

**Issue by fzuchows** [TIBCOSoftware/dovetail#76]
Under https://tibcosoftware.github.io/dovetail/labs/iou-smart-app/ - Step 1.2 the Dovedail Labs docu describes:
1.) create dir structure:
- <base>/tutorial   --> = workspace folder
- <base>/tutorial/artifacts
- <base>/tutorial/network 
- <base>/tutorial/network/fabric
- <base>/tutorial/network/corda 

2.) then
2a.) -> copy [template project](https://github.com/TIBCOSoftware/dovetail/tree/master/docs/content/labs/artifacts/composer-project-template) to the workspace, 
results:
- <base>/tutorial   --> = workspace folder
- <base>/tutorial/artifacts
- <base>/tutorial/network 
- <base>/tutorial/network/fabric
- <base>/tutorial/network/corda 
- <base>/tutorial/composer-project-template --> = project folder
- <base>/tutorial/composer-project-template/models
- <base>/tutorial/composer-project-template/models/dovetail.system.cto
- <base>/tutorial/composer-project-template/README.txt
- <base>/tutorial/composer-project-template/package.json

---> Please note the 's' in models
--Question 1-> Could you please confirm the understanding of the "workspace" and "project"  -or - answer in --Question 3-> ?

2b.) "...and rename the project as iou..."
which results to:
- <base>/tutorial   --> = workspace folder
- <base>/tutorial/artifacts
- <base>/tutorial/network 
- <base>/tutorial/network/fabric
- <base>/tutorial/network/corda 
- <base>/tutorial/iou/models
- <base>/tutorial/iou/models/dovetail.system.cto
- <base>/tutorial/iou/README.txt
- <base>/tutorial/iou/package.json

2c.) then "under folder iou/model, create a file iou.cto" -> please note model, not models
which (would) result to:
- <base>/tutorial   --> = workspace folder
- <base>/tutorial/artifacts
- <base>/tutorial/network 
- <base>/tutorial/network/fabric
- <base>/tutorial/network/corda 
- <base>/tutorial/iou/models
- <base>/tutorial/iou/models/dovetail.system.cto
- <base>/tutorial/iou/model/iou.cto
- <base>/tutorial/iou/README.txt
- <base>/tutorial/iou/package.json

--Question 2-> Could you please let the community know if this the expected directory and file structure -or- is there a typo with the models vs. model ?
--Question 3-> Could you please confirm the structure in 2c.) -or- provide an update ?

Thanks.

**Comment by fzuchows** [comment]
After testing various combinations for 2b.) and 2c.) the correct structure seems to be:
-     /tutorial --> = workspace folder
-     /tutorial/artifacts
-     /tutorial/network
-     /tutorial/network/fabric
-     /tutorial/network/corda
-     /tutorial/iou/models
-     /tutorial/iou/models/dovetail.system.cto
-     /tutorial/iou/models/iou.cto
-     /tutorial/iou/README.txt
-     /tutorial/iou/package.json

-> then the following zip task is fine and the value for "Asset": com.example.iou.IOS appears in the drop-down later in Dovetail Studio.

Result:
-> Documentation issue under https://tibcosoftware.github.io/dovetail/labs/iou-smart-app/
It should be (note the s in models): "under folder iou/models, create a file iou.cto"

**Comment by torresashjian** [comment]
Done
